[PB-11, PB-18, PB-21] Added responsive layout mixins; added sidebar, topic header and article section; added /admin , /resources and /admin/resources pages; updated README.md; general fixes and improvements
Progerbox/progerbox-frontend pull request #6
Opened 2023-03-05 18:13 UTC by HermanTkachenko

2023-03-05 20:47 UTC, SiranWeb requested changes
Pretty good. Just a few changes. And also pay attention to merge conflicts

2023-03-05 20:47 UTC, SiranWeb commented on README.md
> +npm run lint
Remove this line. It's not related to **Run the project**

2023-03-05 20:47 UTC, SiranWeb commented on pages/resources.tsx
> +import { Resources } from "@/pages";
Can you change file path from `pages/resources.tsx` to `pages/resources/index.tsx`?

2023-03-05 20:47 UTC, SiranWeb commented on src/shared/components/header.module.scss
> +}
I like that syntax so much, great job ✊

2023-03-05 20:47 UTC, SiranWeb commented on src/shared/components/layout/articles/articles.tsx
> +export const Articles = ({ }) => { // Thats likely incorrect naming, will need to decide it with team
I will take care of it

2023-03-05 20:47 UTC, SiranWeb commented on src/shared/components/layout/sidebar/sidebarSection.tsx
> +  }>;
It's better to use syntax:
```
{
id: number;
title: string;
}[]
```

2023-03-05 20:47 UTC, SiranWeb commented on src/shared/components/layout/topic/topic.tsx
> +  const { title, description } = topicData[0];
Why you pass here array instead of object?

2023-03-05 20:47 UTC, SiranWeb commented on src/shared/styles/globals.scss
> +  /* GLOBAL PAGE CONTAINER STYLES */
Please, remove comments like that. They are pretty useless and litter the code

2023-03-06 09:32 UTC, HermanTkachenko commented on src/shared/components/layout/topic/topic.tsx
> +  const { title, description } = topicData[0];
made separated array for topic data, i believe putting info inside sidebarData would make more sense 
should i merge topicData with sidebarData?

2023-03-06 10:47 UTC, SiranWeb commented on src/shared/components/layout/topic/topic.tsx
> +  const { title, description } = topicData[0];
I think yes

2023-03-07 12:19 UTC, SiranWeb approved these changes

2023-03-07 12:23 UTC, merged