[PB-31] Added burger menu for sidebar, adjusted container width
Progerbox/progerbox-frontend pull request #9
Opened 2023-03-19 17:20 UTC by HermanTkachenko

TODO: add background blackout once sidebar is toggled ON

2023-03-19 18:00 UTC, SiranWeb requested changes
В целом хорошо, есть пара моментов

2023-03-21 19:00 UTC, SiranWeb requested changes

2023-03-21 19:00 UTC, SiranWeb commented on src/pages/home/ui/home.tsx
> +import { Header } from '@/widgets/header/ui/header';
Аналогично, добавь в `@/widgets/index.ts`

2023-03-22 07:27 UTC, SiranWeb requested changes

2023-03-22 07:27 UTC, SiranWeb commented on src/pages/home/ui/home.tsx
> +import { Header } from '@/widgets/index';
`index` можно не указывать

2023-03-22 09:38 UTC, SiranWeb reviewed
Найс, жду когда закончишь с затемнением

2023-03-22 17:41 UTC, HermanTkachenko commented
![image](https://user-images.githubusercontent.com/51823771/226991675-8a0cd65b-c551-4cd6-b95e-8a3ee14d3a7c.png)

2023-03-22 18:05 UTC, SiranWeb approved these changes
:+1:

2023-03-22 18:05 UTC, SiranWeb commented on src/widgets/header/ui/header.tsx
> +export const Header: FC<Props> = ({ isOpen, onClick }) => {
Может, стоит сделать как и в бургере, дефолтные значения? Чтобы в один момент не поймать `undefined is not a function`

2023-03-22 18:05 UTC, SiranWeb commented on src/widgets/layouts/main-layout/ui/main-layout.tsx
> +    setOpen((prevValue) => !prevValue);
Вообще, prevValue тут необязателен. В этом компоненте нет проблемы с несколькими сет стейтами

2023-03-22 21:03 UTC, SiranWeb approved these changes

2023-03-22 21:03 UTC, SiranWeb commented on src/widgets/header/ui/header.tsx
> +export const Header: FC<Props> = ({ isOpen, onClick = () => {} }) => {
`isOpen = false`

2023-03-22 21:06 UTC, merged